name: queezy_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.2.0
  percent_indicator: ^4.2.5
  pie_chart: ^5.4.0
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  audio_waveforms: ^1.3.0
  permission_handler: ^12.0.1
  flutter_screenutil: ^5.9.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo1.png

flutter_native_splash:
  android_gravity: center
  android: true
  ios: true
  fullscreen: true
  color: "#6A5AE0"
  image: assets/images/logo1.png

flutter:
  uses-material-design: true  
  assets:
    - assets/images/
    - assets/icons/
   
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
    - family: RubikBold
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
    - family: RubikBlack
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf 
    - family: RubikReg
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf 
    - family: RubikMed
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf     
